FROM rocker/verse:4.3.1
RUN apt-get update -y && apt-get install -y  make libcurl4-openssl-dev pandoc zlib1g-dev libbz2-dev liblzma-dev libicu-dev libx11-dev libglpk-dev libxml2-dev libssl-dev libpng-dev git python3 && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = FALSE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "1.0.7")'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
